config/routes.rb
Rails.application.routes.draw do
 
  resources :fronts
 root to: 'recipes#new'
resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController
  def index
    @index
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    recipes = Recipe.all
    render json: { post: recipes }
  end
  def show 
    @recipe = Recipe.find(params[:id])
    recipe = Recipe.find(params[:id])
    render json: { post: recipe }
  end
  def new 
    @recipe = Recipe.new
  end
  def create
    recipe = Recipe.create(recipe_params)
    render json: { post: recipe }
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    recipe = Recipe.update(recipe_params)
    render json: { post: recipe }
  end
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    recipe = Recipe.find(params[:id])
    render json: { post: recipe }
  end


  private
  def recipe_params
    params.require(:recipe).permit(:title, :making_time, :serves, :ingredients, :cost)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/fronts/index.html.erb
<div>
<%=link_to"index", recipes_path %>
</div>
<div>
<%=link_to"new", new_recipe_path %>
</div>
<div>
<%=link_to"create", recipes_path, method: :post%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<%= form_with(model: @recipe, local: true) do |f| %>
      <div class="task-text">title</div>
      <div class="task-container">
      <%= f.text_field :title, placeholder: "例)title", class:"text-area" %>
    </div>
    <div class="time-title">making_time</div>
    <div class="limit_time-container">
      <%= f.text_field :making_time, class:"time-table" %>
    </div>
     <div class="states-title">状態</div>
    <div class="states-container">
    <%= f.text_field :serves, placeholder: "例)2人", class:"text-area" %>
    </div>
     <div class="task-container">
      <%= f.text_field :ingredients, placeholder: "例)にんじん、玉ねぎ", class:"text-area" %>
    </div>
     <div class="task-container">
      <%= f.text_field :cost, placeholder: "例)1000円", class:"text-area" %>
    </div>
    <div class="send-container">
      <%= f.submit "登録する", class:"send-btn" %>
    </div>
    <div class="back-container"><%= link_to '戻る', root_path, class:"back-btn"%></div>
    
    <% end %>

app/views/recipes/index.html.erb
<%@recipes.each do |recipe|%>
<%= link_to recipe_path(recipe.id), method: :get do %>
<%= recipe.title %>
<%= recipe.making_time %>
<%= recipe.serves %>
<%= recipe.ingredients %>
<%= recipe.cost %>
<%end%>
<%end%>

<%@recipes.each do |recipe|%>
<%= link_to recipe_path(recipe.id), method: :get do %>
<span><%= recipe.title %>
<span><%= recipe.making_time %>
<span><%= recipe.serves %>
<span><%= recipe.ingredients %>
<span><%= recipe.cost %>
<%end%>
<%end%>

<div>
<%=link_to "new_action",new_recipe_path%>
</div>

app/views/recipes/new.html.erb
<%= form_with(model: @recipe, local: true) do |f| %>
      <div class="task-text">title</div>
      <div class="task-container">
      <%= f.text_field :title, placeholder: "例)title", class:"text-area" %>
    </div>
    <div class="time-title">making_time</div>
    <div class="limit_time-container">
      <%= f.text_field :making_time, class:"time-table" %>
    </div>
     <div class="states-title">状態</div>
    <div class="states-container">
    <%= f.text_field :serves, placeholder: "例)2人", class:"text-area" %>
    </div>
     <div class="task-container">
      <%= f.text_field :ingredients, placeholder: "例)にんじん、玉ねぎ", class:"text-area" %>
    </div>
     <div class="task-container">
      <%= f.text_field :cost, placeholder: "例)1000円", class:"text-area" %>
    </div>
    <div class="send-container">
      <%= f.submit "登録する", class:"send-btn" %>
    </div>
    <div class="back-container"><%= link_to '戻る', root_path, class:"back-btn"%></div>
    
    <% end %>

app/views/recipes/show.html.erb
<div><%= @recipe.title %></div>
<div><%= @recipe.making_time %></div>
<div><%= @recipe.serves %></div>
<div><%= @recipe.ingredients %></div>
<div><%= @recipe.cost %></div>
<%=link_to "編集", edit_recipe_path(@recipe.id)%>